-- MySQL Script generated by MySQL Workbench
-- Sun May 22 21:36:18 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Game_Collection_Database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Game_Collection_Database` ;

-- -----------------------------------------------------
-- Schema Game_Collection_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Game_Collection_Database` DEFAULT CHARACTER SET utf8 ;
USE `Game_Collection_Database` ;

-- -----------------------------------------------------
-- Table `Game_Collection_Database`.`Publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game_Collection_Database`.`Publisher` ;

CREATE TABLE IF NOT EXISTS `Game_Collection_Database`.`Publisher` (
  `idPublisher` INT NOT NULL AUTO_INCREMENT,
  `Publisher` VARCHAR(100) NOT NULL,
  `Defunct` TINYINT(1) NULL DEFAULT 0,
  `FormerNames` VARCHAR(100) NULL,
  `Notes` VARCHAR(100) NULL,
  PRIMARY KEY (`idPublisher`),
  UNIQUE INDEX `Publisher_UNIQUE` (`Publisher` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game_Collection_Database`.`Developer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game_Collection_Database`.`Developer` ;

CREATE TABLE IF NOT EXISTS `Game_Collection_Database`.`Developer` (
  `idDeveloper` INT NOT NULL AUTO_INCREMENT,
  `Developer` VARCHAR(100) NOT NULL,
  `Defunct` TINYINT(1) NULL DEFAULT 0,
  `FormerNames` VARCHAR(100) NULL,
  `Notes` VARCHAR(100) NULL,
  PRIMARY KEY (`idDeveloper`),
  UNIQUE INDEX `Developer_UNIQUE` (`Developer` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game_Collection_Database`.`GameSystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game_Collection_Database`.`GameSystem` ;

CREATE TABLE IF NOT EXISTS `Game_Collection_Database`.`GameSystem` (
  `idGameSystem` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `ShortName` VARCHAR(10) NULL,
  `Notes` VARCHAR(100) NULL,
  `Publisher` INT NOT NULL,
  PRIMARY KEY (`idGameSystem`),
  INDEX `publisherId_idx` (`Publisher` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  CONSTRAINT `publisherId`
    FOREIGN KEY (`Publisher`)
    REFERENCES `Game_Collection_Database`.`Publisher` (`idPublisher`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game_Collection_Database`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game_Collection_Database`.`Game` ;

CREATE TABLE IF NOT EXISTS `Game_Collection_Database`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Publisher` INT NOT NULL,
  `Developer` INT NOT NULL,
  `System` INT NOT NULL,
  `Website` VARCHAR(100) NULL,
  `Price` VARCHAR(45) NULL,
  `MarkedToSell` TINYINT(1) NULL,
  `Multiplayer` TINYINT(1) NULL,
  `MutiplayerActiveStatus` TINYINT(1) NULL,
  `PlayerCount` VARCHAR(100) NULL,
  `Notes` VARCHAR(100) NULL,
  PRIMARY KEY (`idGame`),
  INDEX `Developer_idx` (`Developer` ASC),
  INDEX `VideoGameSystem_idx` (`System` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  CONSTRAINT `Developer`
    FOREIGN KEY (`Developer`)
    REFERENCES `Game_Collection_Database`.`Developer` (`idDeveloper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Publisher`
    FOREIGN KEY (`Publisher`)
    REFERENCES `Game_Collection_Database`.`Publisher` (`idPublisher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VideoGameSystem`
    FOREIGN KEY (`System`)
    REFERENCES `Game_Collection_Database`.`GameSystem` (`idGameSystem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
